### PR TITLE
fix: format and wording adjustments in workspaces, contributors and repo insights sections 

### LINKED ISSUE #261: Docs: Fix format and adjust wording in workspaces page
## Description

There are format fixes and wording adjustments that need to be made to the new Workspaces and the updated Repository and Contributor Insights docs for clarity and consistency.
This issue refers to PR #255.

### LINKED ISSUE #266: Remove information about Reports from docs
With the updates to workspaces, we've removed the Reports feature (for now). To keep the docs up to date, we need to remove mentions of it throughout our docs as well.

### PR DESCRIPTION
**Pull request by adiati98**
## Description

This PR fixes format and adjusts wording in workspaces, contributors and the repo insights sections, as well as sections that need to be updated with this new feature.

This changes are related to PR #255 

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

- Fixes #261 
- Closes #266 

## Added to documentation?

- [ ] 📜 README.md
- [x] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

File: sidebars.js [hunk 1]
```diff
@@ -26,6 +26,7 @@ module.exports = {
         "features/workspaces",
         "features/repo-insights",
         "features/contributor-insights",
+        "features/connections",
```
Comment (BekahHW) [inline sidebars.js:29]: I intentionally removed this from the sidebar.

Comment (adiati98) [reply sidebars.js:29]: I'll change it back 👍

File: docs/features/repo-insights.md
Comment (adiati98) [inline docs/features/repo-insights.md:1]: After we log in to our account and click the "Workspaces" tab, we will see "PERSONAL WORKSPACE" with an "Add repositories" button.

Screenshot 2024-02-28 165912

We haven't explained what this is in the Contributors and Maintainers guides. We might want to explain about it there or any other suitable section in one point.

I have a question on this: what are the difference between creating personal workspace and creating repository insights page?

**Review by adiati98 — COMMENTED** [review]
Hi @BekahHW 

This PR is ready for review, and I'm leaving here some comments and questions.

Thank you! 😊

File: docs/features/contributor-insights.md
[the remark this answers is not in the document]
Comment (BekahHW) [reply docs/features/contributor-insights.md:1]: You're right. Those bullet points are accurate. 

So it should be:

After logging in, navigate to the Insights link in the sidebar. Click the '+' to be presented with options and select New Contributor Insight.

File: docs/features/repo-insights.md
Comment (BekahHW) [reply docs/features/repo-insights.md:1]: I have an issue up to add it to the guides. 

Currently, the difference is in the metrics that are shown. We'll be adding more features to the personal workspace though. 

This is what the workspace looks like

image

File: docs/features/workspaces.md [hunk 2]
```diff
@@ -25,22 +25,21 @@ By default, all workspaces are public. This means that anyone with the link to y
...
- - Links to support.
+- Options for creating and viewing workspaces.
+- Access to your Contributor and Repository Insights pages.
+- Links to support.
 
- ![Sidebar](../../static/img/workspace-sidebar.png)
+![Sidebar](../../static/img/workspace-sidebar.png)
 
-:::tip
+:::info
```
[the remark this answers is not in the document]
Comment (BekahHW) [reply docs/features/workspaces.md:34]: That's great. I didn't realize that we had access to info too. Or maybe I forgot.

[the remark this answers is not in the document]
Comment (adiati98) [reply docs/features/workspaces.md:34]: There are tip, info, note, warning, and danger.

But FYI, the warning appears as danger. I wanted to raise an issue for this at Docusaurus, but I'm not sure if this is fixed in version 3, and we're using version 1.

File: docs/features/contributor-insights.md
[the remark this answers is not in the document]
Comment (adiati98) [reply docs/features/contributor-insights.md:1]: So, the path is still using `.../hub/lists/`?

File: docs/features/repo-insights.md
Comment (adiati98) [reply docs/features/repo-insights.md:1]: So, is it safe to say that personal space is the place for us to list, say, favorite repositories to track PR, issues and engagements?

Because we can only add repositories and can't add more personal workspace.

File: docs/features/workspaces.md [hunk 3]
```diff
@@ -11,7 +11,7 @@ keywords:
   - "open source contributors"
 ---
 
-In the OpenSauced app, your work unfolds within a Workspace, a virtual environment designed to organize information for yourself, collaborating as a team, or operating across an entire company. Workspaces are a place to share, collaborate, and track open source projects and  contributors.
+In the OpenSauced app, your work unfolds within a Workspace, a virtual environment designed to organize information for yourself, collaborating as a team, or operating across an entire company. Workspaces is a place to share, collaborate, and track open source projects and contributors.
```
Comment (BekahHW) [inline docs/features/workspaces.md:14]: I don't love the way I have this worded. Let's make these adjustments:

In the OpenSauced app, your work unfolds within a Workspace: a virtual environment for managing information—whether for individual productivity, team collaboration, or company-wide operations. Workspaces serve as a centralized hub for sharing, collaborating on, and monitoring open source projects and their contributors. This feature is designed to streamline your open source involvement, making it more efficient and interconnected.

**Review by BekahHW — CHANGES_REQUESTED** [review]
This is great. Thanks, Ayu. I left some comments.

**Comment by adiati98** [comment]
@BekahHW I've changed the wording as per your request. Ready for final review!

File: docs/features/workspaces.md (hunk 2 above)
[the remark this answers is not in the document]
Comment (BekahHW) [reply docs/features/workspaces.md:34]: I just made an issue to upgrade. I'll do that in the next week or two.

File: docs/features/repo-insights.md
Comment (BekahHW) [reply docs/features/repo-insights.md:1]: That's fair to say, although that won't be everyone's usecase. For example, I might have the repos I actively maintain, repos of companies I'm applying to, etc.

Comment (adiati98) [reply docs/features/repo-insights.md:1]: Ah, I see.
Because before there's a personal workspace, I have a [list of repos that I maintain in an (previously) Insights page](https://app.opensauced.pizza/workspaces/d4656059-fd80-487e-8600-a7c915f83b2f/repository-insights/1122/dashboard).

Comment (adiati98) [reply docs/features/repo-insights.md:1]: > Maybe there's need for some clarification here. If you want Repository Insights, you click the '+' next to insights in the sidebar.

We have this mentioned in the Contributors guide.

Screenshot 2024-02-28 205851

But we haven't mentioned about the "+" sign in the maintainer guide.

Screenshot 2024-02-28 210216

Comment (BekahHW) [reply docs/features/repo-insights.md:1]: yes

File: docs/maintainers/maintainers-guide.md [hunk 4]
```diff
@@ -43,25 +43,25 @@ There are two ways to add repositories to your Repository Insight Page:
 
 ### Using Your Repository Insights Page
 
-Once you have connected your repositories, you will be redirected to your Insight Page. Here, you will see a dashboard with an overview of the repositories and the contributors who have contributed to them.
+Once you have connected your repositories, you will be redirected to your Repository Insight Page. Here, you will see a dashboard with an overview of the repositories and the contributors who have contributed to them.
```
Comment (adiati98) [inline docs/maintainers/maintainers-guide.md:46]: Can you help to double check this with me?

Because after I created a repository insights page, it redirected me to the "Personal Workspace" instead of the new created page as screen recording below.

create new repo insights 1

File: docs/maintainers/maintainers-guide.md [hunk 5]
```diff
@@ -43,25 +43,25 @@ There are two ways to add repositories to your Repository Insight Page:
...
 
 There are three tabs that provide you with more information on these repositories:
 
 #### Reports
```
Comment (adiati98) [inline docs/maintainers/maintainers-guide.md:50]: I don't see "Reports" tab in on the Repository Insight Page. There are only "Dashboard", "Contributors" and "Activity".

Screenshot 2024-02-28 215744

File: docs/maintainers/maintainers-guide.md [hunk 6]
```diff
@@ -43,25 +43,25 @@ There are two ways to add repositories to your Repository Insight Page:
...
 
 ![repositories tab](../../static/img/repos-insights.png)
 
 #### Contributors
 
-The Contributors tab allows you to view more detailed information on each contributor, including Activity, Repositories, the date of their last contribution, Time Zone, and the number of contributions.
+The "Contributors" tab allows you to view more detailed information on each contributor, including Activity, Repositories, the date of their last contribution, Time Zone, and the number of contributions.
 
-To learn more about your contributors, you can select them and add them to a Contributor Insight Page.
+You can select and add your contributors to a Contributor Insight Page to learn more about them.
```
Comment (adiati98) [inline docs/maintainers/maintainers-guide.md:64]: Should we link the contributor insight page to the next section or leave it as is?

```suggestion
You can select and add your contributors to a [Contributor Insight Page](#contributor-insights-connecting-with-contributors) to learn more about them.
```

File: docs/maintainers/maintainers-guide.md [hunk 7]
```diff
@@ -70,39 +70,39 @@ There are two ways to add contributors to a Contributor Insight Page:
 1. Create a new Contributor Insight Page with selected contributors.
 2. Add selected contributors to an existing Contributor Insight Page.
```
Comment (adiati98) [inline docs/maintainers/maintainers-guide.md:71]: I'm thinking to move line 68-71 to before the image so it won't be missed. Thoughts?

File: docs/contributors/contributors-guide.md [hunk 8]
```diff
@@ -145,7 +149,9 @@ The "Contributors" tab allows you to view more detailed information about other
 ![contributors insight list](../../static/img/contributors-insights.png)
 
 :::tip
+
 Want to learn more about your peers? You can select them and add them to a list.
+
 :::
 
 To learn more about these features, see [Understanding Repository Insights Data](../maintainers/understanding-repo-insights.md).
```
Comment (adiati98) [inline docs/contributors/contributors-guide.md:157]: As we're talking about how to read and understand the data, we might be able to clarifiy this with wording adjustment as below:

```suggestion
To learn and understand more about the data provided, see [Understanding Repository Insights Data](../maintainers/understanding-repo-insights.md).
```

Any other idea on the wording?

If we agreed on the wording, we might as well will reword the same sentence in the maintainer guide.

Comment (CBID2) [reply docs/contributors/contributors-guide.md:157]: How about this way @adiati98? It’ll clarify to current and potential users to expand their knowledge a bit more.

```suggestion
Want to learn other ways to use these features? Check out [Understanding Repository Insights Data](../maintainers/understanding-repo-insights.md).
```

File: docs/features/contributor-insights.md
[the remark this answers is not in the document]
Comment (adiati98) [reply docs/features/contributor-insights.md:1]: Sorry, my brain fried last  night 😆.
I'll change the wording. And leave out the link?

File: docs/contributors/contributors-guide.md [hunk 9]
```diff
@@ -160,16 +166,17 @@ There are many things you can do with this feature, but here are some ideas to g
 
 - **Track personal contributions**: If you create a list of your personal contributions, you can track them and see how you're doing over time, as well as get a breakdown of the type of contributions you're making, including commits, created PRs, reviewed PRs, and created issues.
 - **Learn about what other contributors are doing in open source**: You can learn where other contributors are contributing, what they're working on, and how active they are in the open source community.
-- **See who's using OpenSauced Highlights feature**: You can see who's using the Highlights feature and show them support by giving an emoji reaction.
+- **See who's using the OpenSauced Highlights feature**: You can see who's using the Highlights feature and show them support by giving an emoji reaction.
```
Comment (CBID2) [inline docs/contributors/contributors-guide.md:169]: [improvement] Here, it would be beneficial to point out a aspect of open source & how the OpenSauced feature can facilitate it. What do you think @adiati98?
```suggestion
- **Support other contributors**: Networking with others is key to thriving in open source. You can do this by posting a emoji  on someone’s highlight in the Highlights section.
```

File: docs/features/connections.md [hunk 10]
```diff
@@ -10,19 +10,20 @@ keywords:
...
+  - "grow network"
   - "grow connection"
   - "Community connections"
-
 ---
 
 ## What are Connections?
 
-Connections on OpenSauced serve as a way to build and nurture your professional network within the open source ecosystem. Imagine you're searching for experts in Artificial Intelligence using our [Contributor Insights](contributor-insights.md) feature, and you come across several promising developers. What's next? With Connections, you can now send a request to connect, bringing these experts into your professional circle for easy communication and collaboration.
+Connections on OpenSauced serve as a way to build and nurture your professional network within the open source ecosystem. Imagine you're searching for experts in Artificial Intelligence using our [Contributor Insights](contributor-insights.md) feature, and you come across several promising developers. What's next?
```
Comment (CBID2) [inline docs/features/connections.md:20]: [improvement] I think the wording here could be improved. It’s already been established that the features are apart of OpenSauced, so I think it is best to be a bit more straightforward at the beginning of this paragraph. Thoughts? 
```suggestion
This feature can help you build and nurture your professional network within the open source ecosystem. Imagine you're searching for experts in Artificial Intelligence using our [Contributor Insights](contributor-insights.md) feature, and you come across several promising developers. What's next?
```

File: docs/maintainers/maintainers-guide.md [hunk 11]
```diff
@@ -70,39 +70,39 @@ There are two ways to add contributors to a Contributor Insight Page:
...
+## Contributor Insights: Connecting with Contributors
 
 OpenSauced Contributor Insights feature allows you to categorize, monitor, and analyze various groups of contributors. You can use Contributor Insights to track the contributions of a specific team, a specific repository, or a group of repositories. This feature offers granular insights into each contributor's activities and contributions, helping maintainers to track individual contribution histories, identify active engagement, recognize new or alumni contributors, and compare the performance of different contributors.
 
 The Contributor Insights features allow you to:
 
 - track the commits and PRs of the contributors on your list,
 - filter your contributors by their activity level, including most active, new, and alumni,
-- view the repositories that your contributors have contributed to, the top programming languages they've used, and their time zones.
+- view the repositories your contributors have contributed to, the top programming languages they've used, and their time zones.
```
Comment (CBID2) [inline docs/maintainers/maintainers-guide.md:81]: [improvement] the wording here could be clearer. Thoughts?
```suggestion
- view the repositories your contributors have worked on, the top programming languages they've used, and their time zones.
```

File: docs/maintainers/maintainers-guide.md [hunk 12]
```diff
@@ -70,39 +70,39 @@ There are two ways to add contributors to a Contributor Insight Page:
...
+- **VIP contributors**: Highlight and track contributors you've identified as key maintainers or significant contributors.
 - **Sales leads**: Identify contributors whose engagement could potentially be turned into sales opportunities.
 - **Potential hires**: Observe contributors who exhibit skill and commitment, making them prime candidates for hiring.
 - **Alumni contributors**: Keep an eye on contributors who have decreased their engagement or left the project.
 
 ### Creating a New Contributor Insight Page
 
-1. Click the + next to Insights in the sidebar to create a new insight page. You will be redirected to a page where you can create your new insight page.
+1. Click the "+" next to "Insights" in the sidebar.
+2. Click "New Contributor Insight". You will be redirected to a page where you can create your new Contributor Insight Page.
```
Comment (CBID2) [inline docs/maintainers/maintainers-guide.md:97]:
```suggestion
2. Click "New Contributor Insight". From there, you will be redirected to a page where you can create your new Contributor Insight Page.
```

File: docs/maintainers/maintainers-guide.md [hunk 13]
```diff
@@ -70,39 +70,39 @@ There are two ways to add contributors to a Contributor Insight Page:
...
 
-![New Contributor Insight Page](../../static/img/contrib-insight-new.png)
+   ![New Contributor Insight Page](../../static/img/contrib-insight-new.png)
 
-2. Click on the "New Contributor Insight" to start a new insight page.
 3. Give your page a name.
 4. Choose your page visibility. You can choose to make your Contributor Insight Page public or private. By default, it is set to public.
```
Comment (CBID2) [inline docs/maintainers/maintainers-guide.md:102]:
```suggestion
4. Choose your page visibility. By default, your Contributors Insight page is set to public, but can you make it private.
```

File: docs/maintainers/maintainers-guide.md [hunk 14]
```diff
@@ -112,25 +112,25 @@ There are three tabs that provide you with more information on these repositorie
 
 ### Overview
 
-The Overview tab gives you a high-level view of the contributors in your Contributor Insight Page, including the total number of commits in the last 30 days and the types of contributors: Active, New, and Alumni.
+The "Overview" tab gives you a high-level view of the contributors in your Contributor Insight Page, including the total number of commits in the last 30 days and the types of contributors: Active, New, and Alumni.
 
 ### Activity
 
-The Activity tab gives you a graph view with more detailed information on each contributor, including the type of activity, repositories they've contributed to, and how they compare to each other.
+The "Activity" tab gives you a graph view with more detailed information on each contributor, including the type of activity, repositories they've contributed to, and how they compare to each other.
```
Comment (CBID2) [inline docs/maintainers/maintainers-guide.md:119]:
```suggestion
The "Activity" tab gives you a graph with detailed information on each contributor, including the type of activity, repositories they've contributed to, and how they compare to each other.
```

File: docs/maintainers/maintainers-guide.md [hunk 15]
```diff
@@ -112,25 +112,25 @@ There are three tabs that provide you with more information on these repositorie
...
 
 You can filter your Contributor Insight Page by All Contributors, Active Contributors, New Contributors, and Alumni Contributors.
```
Comment (CBID2) [inline docs/maintainers/maintainers-guide.md:121]:
```suggestion
You can filter your Contributor Insight Page by choosing All Contributors, Active Contributors, New Contributors, or Alumni Contributors.
```

File: docs/maintainers/maintainers-guide.md [hunk 16]
```diff
@@ -142,7 +142,7 @@ Highlights can be used to:
 
 There are two ways to create a new highlight:
 
-1. After clicking the [Highlights tab](https://app.opensauced.pizza/feed) in the top navigation, click the input that says "Post a highlight to show your work!"
+1. After clicking the "[Highlights](https://app.opensauced.pizza/feed)" tab in the top navigation, click the input that says "Post a highlight to show your work!"
 
 2. From your profile, click the input that says "Post a highlight to show your work!"
```
Comment (CBID2) [inline docs/maintainers/maintainers-guide.md:147]: [suggestion] We mentioned this part in the previous step, so I think it is best to omit this part. Thoughts?
```suggestion
```

**Review by CBID2 — COMMENTED** [review]
Here’s what I have as feedback for now @adiati98. Going to do more later. Keep up the good work! :)

File: docs/features/contributor-insights.md
[the remark this answers is not in the document]
Comment (BekahHW) [reply docs/features/contributor-insights.md:1]: There's no longer a path that takes you directly there. So leave it out.

File: docs/maintainers/maintainers-guide.md (hunk 4 above)
Comment (BekahHW) [reply docs/maintainers/maintainers-guide.md:46]: Just created a bug report for that.

File: docs/contributors/contributors-guide.md (hunk 8 above)
Comment (adiati98) [reply docs/contributors/contributors-guide.md:157]: In my understanding, what we want to say here is for folks to learn about how to read and understand the data provided in each tab. And these are not part of features.

Would love to hear @BekahHW opnion about this.

File: docs/features/connections.md (hunk 10 above)
Comment (adiati98) [reply docs/features/connections.md:20]: We don't make any content changes here as we want to leave out this section for now.
The only change here was a minor format.

But thanks for the input. 👍

File: docs/maintainers/maintainers-guide.md (hunk 11 above)
Comment (adiati98) [reply docs/maintainers/maintainers-guide.md:81]: I think "contributed to" is make much more sense here.

File: docs/maintainers/maintainers-guide.md [hunk 17]
```diff
@@ -142,7 +142,7 @@ Highlights can be used to:
 
 There are two ways to create a new highlight:
 
-1. After clicking the [Highlights tab](https://app.opensauced.pizza/feed) in the top navigation, click the input that says "Post a highlight to show your work!"
+1. After clicking the "[Highlights](https://app.opensauced.pizza/feed)" tab in the top navigation, click the input that says "Post a highlight to show your work!"
```
[the remark this answers is not in the document]
Comment (adiati98) [reply docs/maintainers/maintainers-guide.md:145]: If you see the app, the input does say "Post a highlight to show your work!"

Screenshot 2024-02-29 200329

File: docs/maintainers/maintainers-guide.md (hunk 13 above)
Comment (adiati98) [reply docs/maintainers/maintainers-guide.md:102]: I feel like the original is more clear and in the flow here.
But I'll let @BekahHW decide. 🙂

Also, it supposed to be "Contributor Insight Page", and not "Contributors Insight page".

File: docs/maintainers/maintainers-guide.md [hunk 18]
```diff
@@ -25,14 +25,14 @@ OpenSauced Repository Insights provides maintainers with a visual representation
...
+- view the number of PRs that are open, closed, in draft, and merged,
+- view the average number of days it takes for a PR to be merged (PR velocity),
 - identify the top contributors to your project,
-- identify the current activity level and trends in activity of your contributors.
+- identify the current activity level and trends in the activity of your contributors.
 
 ### Creating a New Repository Insight Page
 
-To connect your repositories, click the "Insights" tab on the dashboard. You will be redirected to a page where you can create your new Repository Insight Page.
+To connect and track your repositories, click the "+" next to "Insights" in the sidebar, then select "New Repository Insight". You will be redirected to a page where you can create your new Repository Insight Page.
```
Comment (CBID2) [inline docs/maintainers/maintainers-guide.md:35]:
```suggestion
To connect and track your repositories, click the "+" next to "Insights" in the sidebar, and select "New Repository Insight". From there, you will be redirected to a page where you can create your new Repository Insight Page.
```

File: docs/maintainers/maintainers-guide.md (hunk 5 above)
Comment (CBID2) [reply docs/maintainers/maintainers-guide.md:50]: Hi @adiati98. Repositories section does sound clearer.

File: docs/maintainers/maintainers-guide.md (hunk 7 above)
Comment (CBID2) [reply docs/maintainers/maintainers-guide.md:71]: That would help @adiati98. It'll make the instructions clearer for contributors.

File: docs/maintainers/maintainers-guide.md (hunk 11 above)
Comment (CBID2) [reply docs/maintainers/maintainers-guide.md:81]: I don't know @adiati98. Saying "contributors have contributed to" does sound a bit redundant, so using a different word like "worked on" conveys the same point but in a clearer way. What do you think @BekahHW?

File: docs/contributors/contributors-guide.md (hunk 8 above)
Comment (BekahHW) [reply docs/contributors/contributors-guide.md:157]: @adiati98's correct here.

File: docs/contributors/contributors-guide.md (hunk 9 above)
Comment (BekahHW) [reply docs/contributors/contributors-guide.md:169]: @CBID2 that's out of the scope of this PR.

File: docs/maintainers/maintainers-guide.md (hunk 12 above)
Comment (BekahHW) [reply docs/maintainers/maintainers-guide.md:97]: @CBID2 punctuation should go inside the quotes. I also don't feel this updates are necessary.

File: docs/maintainers/maintainers-guide.md (hunk 13 above)
Comment (BekahHW) [reply docs/maintainers/maintainers-guide.md:102]: These are fine as they stand.

File: docs/maintainers/maintainers-guide.md [hunk 19]
```diff
@@ -155,8 +155,12 @@ There are two ways to create a highlight:
 
 ![highlight suggestions](../../static/img/highlights.png)
 
+:::note
+
 If you're adding a blog post, you'll need to associate it to a repository by clicking the "Add a repo" button.
```
[the remark this answers is not in the document]
Comment (BekahHW) [reply docs/maintainers/maintainers-guide.md:160]: @CBID2 there's an issue and discussion in the app repo about connecting it that you can check out.

File: docs/maintainers/maintainers-guide.md (hunk 5 above)
Comment (adiati98) [reply docs/maintainers/maintainers-guide.md:50]: Repositories Dashboard sounds great!

Also, I'll remove Reports altogether with this PR. 👍

File: docs/contributors/contributors-guide.md [hunk 20]
```diff
@@ -125,30 +129,35 @@ There are two ways to add repositories to your Repository Insight Page:
...
-To learn more about these features, see [Understanding Repository Insights Data](../maintainers/understanding-repo-insights.md).
+To learn and understand more about the data provided, see [Understanding Repository Insights Data](../maintainers/understanding-repo-insights.md).
+
+#### Activity
+
+The "Activity" tab shows a graph of the last time each contributor created their PR and how many lines of code they've touched.
+
+It also provides more detailed information on each contributor when you hover over their image, including their latest PRs and repositories they've contributed to. Clicking their image will bring you to their profile on OpenSauced. This information can help you find potential repositories to contribute to and peers to collaborate with or ask for mentorship.
+
+![activity graph](../../static/img/activity-repos-insights.png)
```
Comment (adiati98) [inline docs/contributors/contributors-guide.md:160]: I added the Activity tab subsection, as well as an image fo the tab.
I'm not sure if you're intentionally leave it out. So please let me know if I need to remove it.

I also added the same subsection for the Maintainers Guide. Wordings are the same. The difference is the purpose of this tab for contributor and maintainer, which I need you to check.

Thanks! 😊

File: docs/features/workspaces.md [hunk 21]
```diff
@@ -52,26 +51,24 @@ Within the repositories dashboard, you can view the following metrics, which are
 - **Issues**: This includes the total Opened and Closed Issues for the repositories included in your workspace, as well as the velocity of issues being closed.
 - **Engagement**: This includes the total stars, forks, and activity ratio for the repositories included in your workspace.
 
-
 ## How to Create or Access a Workspace
 
 To create a workspace, start by accessing the **Workspace switcher** in the sidebar. From there, you can create a new workspace or view an existing one.
```
Comment (adiati98) [inline docs/features/workspaces.md:56]: To clarify "Workspace switcher", can we say something like this?

```suggestion
To create a workspace, start by accessing the dropdown menu (Workspace switcher) in the sidebar. From there, you can create a new workspace or view an existing one.
```

File: docs/features/workspaces.md [hunk 22]
```diff
@@ -25,22 +25,21 @@ By default, all workspaces are public. This means that anyone with the link to y
...
+- Links to support.
 
- ![Sidebar](../../static/img/workspace-sidebar.png)
+![Sidebar](../../static/img/workspace-sidebar.png)
 
-:::tip
+:::info
 
- We recently had a naming change. The Contributors Insights section was previously called [Lists](contributor-insights.md), and the Repositories Insights section was previously called [Insights](./repo-insights.md).
+We recently had a naming change. The [Contributors Insights](contributor-insights.md) section was previously called Lists, and the [Repositories Insights](./repo-insights.md) section was previously called Insights.
```
Comment (adiati98) [inline docs/features/workspaces.md:36]: Do we need to mention "section" here as in Contributors Insights section?
I'm thinking as we're talking about features, we can omit the word "section". Or, change it with "feature".

```suggestion
We recently had a naming change. The [Contributors Insights](contributor-insights.md) feature was previously called Lists, and the [Repositories Insights](./repo-insights.md) feature was previously called Insights.
```

File: docs/maintainers/understanding-repo-insights.md [hunk 23]
```diff
@@ -13,10 +13,9 @@ keywords:
   - "Data Interpretation Methods"
   - "Insightful Data Examination"
   - "Guide to Understanding Data"
-
 ---
 
-Once your repositories are connected, it's time to understand the data provided in your Insight Page. Understanding this data is key to effectively managing your projects and contributors.
+Once your repositories are connected, it's time to understand the data provided in your page. Understanding this data is key to effectively managing your projects and contributors.
 
 ## Understanding Repository Insights Data
```
Comment (adiati98) [inline docs/maintainers/understanding-repo-insights.md:20]: Because the main title is "Understanding Repo Insights Data", I'm thinking that we might able to adjust this title to be:

```suggestion
## Understanding Repository Dashboard Data
```

Any thoughts on this?

File: docs/maintainers/maintainers-guide.md [hunk 24]
```diff
@@ -43,66 +43,72 @@ There are two ways to add repositories to your Repository Insight Page:
...
 ![contributors insight list](../../static/img/contributors-insights.png)
 
-There are two ways to add contributors to a Contributor Insight Page:
+#### Activity
+
+The "Activity" tab shows a graph of the last time each contributor created their PR and how many lines of code they've touched.
 
-1. Create a new Contributor Insight Page with selected contributors.
-2. Add selected contributors to an existing Contributor Insight Page.
+It also provides more detailed information on each contributor when you hover over their image, including their latest PRs and repositories they've contributed to. Clicking their image will bring you to their profile on OpenSauced. You can use the information in this tab to help you learn about their engagement and general interests. It will be helpful if you want to collaborate with them or consider recruiting a maintainer for your project.
```
Comment (adiati98) [inline docs/maintainers/maintainers-guide.md:75]: This is the "Activity" tab subsection that I added for the Maintainers Guide. Same wording, different purpose that's shown in the last two sentences here.

**Review by adiati98 — COMMENTED** [review]
Hey @BekahHW 

I left some comments to get your thoughts here.
I'll reread everything one more time tomorrow.

Thank you! 😄

File: docs/maintainers/maintainers-guide.md [hunk 25]
```diff
@@ -43,66 +43,72 @@ There are two ways to add repositories to your Repository Insight Page:
...
 
-2. Click on the "New Contributor Insight" to start a new insight page.
 3. Give your page a name.
 4. Choose your page visibility. You can choose to make your Contributor Insight Page public or private. By default, it is set to public.
 5. Add contributors to your page by searching for their GitHub username, syncing your GitHub Team, or importing your GitHub Following.
 
-![team sync gif](../../static/gif/team-sync.gif)
+   ![team sync gif](../../static/gif/team-sync.gif)
 
 ## Using Your Contributor Insight Page
```
Comment (adiati98) [inline docs/maintainers/maintainers-guide.md:113]: In this section, there are three tabs explained: Overview, Activity, and Contributor.
With the new workspace, we now have: Overview, Activity, and Highlights (see screenshot below).

We might want to update this as well as add a new image to replace the one in "Activity" subsection. We can add it here or create a new issue for that.

Screenshot 2024-03-03 234339

Comment (CBID2) [reply docs/maintainers/maintainers-guide.md:113]: > In this section, there are three tabs explained: Overview, Activity, and Contributor.
> 
> With the new workspace, we now have: Overview, Activity, and Highlights (see screenshot below).
> 
> 
> 
> We might want to update this as well as add a new image to replace the one in "Activity" subsection. We can add it here or create a new issue for that.
> 
> 
> 
> Screenshot 2024-03-03 234339
> 
> 
> 
> 
> 
> 

I think creating a separate issue for this would be good @adiati98. If you & @BekahHW go with this idea, I'll create the issue for it.

File: docs/features/workspaces.md (hunk 21 above)
Comment (BekahHW) [reply docs/features/workspaces.md:56]: I would rather keep the terminology and add a screenshot with the switcher highlighted. 

This is how Notion has it.

image

File: docs/maintainers/maintainers-guide.md (hunk 24 above)
Comment (BekahHW) [reply docs/maintainers/maintainers-guide.md:75]: Sounds good.

File: docs/maintainers/maintainers-guide.md (hunk 25 above)
Comment (BekahHW) [reply docs/maintainers/maintainers-guide.md:113]: I would rather have a new issue for this, just so we can get this merged in.

Comment (CBID2) [reply docs/maintainers/maintainers-guide.md:117]: Ok I'll create the issue

Comment (adiati98) [reply docs/maintainers/maintainers-guide.md:117]: @CBID2 I've changed this to "Highlights".
I just noticed we have it in the contributor section. So, I use that one.

Comment (CBID2) [reply docs/maintainers/maintainers-guide.md:117]: Hey @adiati98. I just saw this message. I made [the issue](https://github.com/open-sauced/docs/issues/270). Since we don't need it yet, I kept it in triage mode. Is that ok?

File: docs/contributors/contributors-guide.md [hunk 26]
```diff
@@ -35,41 +40,45 @@ Your profile is a great resource for showcasing your contributions and sharing y
...
 - **Recommendations**: This tab includes a list of open source projects that are chosen based on the programming languages you picked in the "Interests" section of your public profile. It is useful if you're looking for new projects to contribute to.
 
 ## Explore: Finding Your Next Open Source Project
 
 The "Explore" tab is a great place to start if you're looking for a new open source project to contribute to or want to find repositories for potential job opportunities. Here, you can find a list of open source projects and filter them by language, top repos, recent, most active, and more.
 
-Once you've selected your filters, you'll be able to see the contributors, spam, and activity levels of the repository. Understanding the activity level and PR velocity of a repository can help you determine if it's a good fit for you to contribute to and what to expect when you submit a PR.
+Once you've selected your filters, you'll be able to see the contributors, spam, and activity levels of the repository. Understanding a repository's activity level and PR velocity can help you determine if it's a good fit for you to contribute to and what to expect when you submit a PR.
```
Comment (adiati98) [inline docs/contributors/contributors-guide.md:53]: Just a note:

We might want to revisit this. I'm not sure here are we talking about the higher view (Contributors, Spam, Merged PRs, and Unlabeled PRs) or the data in the Repositories.

File: docs/maintainers/maintainers-guide.md [hunk 27]
```diff
@@ -43,66 +43,76 @@ There are two ways to add repositories to your Repository Insight Page:
...
 
-![New Contributor Insight Page](../../static/img/contrib-insight-new.png)
+   ![New Contributor Insight Page](../../static/img/contrib-insight-new.png)
 
-2. Click on the "New Contributor Insight" to start a new insight page.
 3. Give your page a name.
-4. Choose your page visibility. You can choose to make your Contributor Insight Page public or private. By default, it is set to public.
-5. Add contributors to your page by searching for their GitHub username, syncing your GitHub Team, or importing your GitHub Following.
+4. Add contributors to your page by searching for their GitHub username, syncing your GitHub Team, or importing your GitHub Following.
+5. Choose your page visibility. You can choose to make your Contributor Insight Page public or private. By default, it is set to public.
```
Comment (adiati98) [inline docs/maintainers/maintainers-guide.md:113]:
```suggestion
5. Once your page is created, you can edit and choose to make it public or private. By default, it is set to public. To create a private page, you can upgrade your account to a paid plan.
```

File: docs/features/workspaces.md [hunk 28]
```diff
@@ -25,53 +25,50 @@ By default, all workspaces are public. This means that anyone with the link to y
...
+Whenever you select "Home", you'll be taken to the last workspace you opened.
 
 :::
 
 ### How to Add Repositories to a Workspace
 
 If you're creating a new workspace, you'll have the option to add repositories at the time of creation.
 
-Start by creating a Workspace name, and then click `Add repositories`. You'll have three options for adding repositories:
+Start by creating a workspace name, then click "Add repositories." You'll have three options for adding repositories:
```
[the remark this answers is not in the document]
Comment (BekahHW) [reply docs/features/workspaces.md:72]: I think there are two issues here: Maybe the issue here is "How to Add repositories to a workspace" and "How to Add Repos to Your Personal Workspace."

We can have two separate lines.

- **Adding repos to a workspace**- {description}
- **Adding repos to your personal workspace** - {Deseciption}

I _believe_ that only the personal workspace has the edit button. That's because it also takes you to the settings page where you can add workspace members, change the visibility, and upgrade. Which is something I'm going to add to the docs after we get this merged in.

File: docs/contributors/contributors-guide.md [hunk 29]
```diff
@@ -125,51 +134,56 @@ There are two ways to add repositories to your Repository Insight Page:
...
-1. Click the "+" next to Insights in your side bar. "Contributor Insights" tab on the Repository Insights hub to create a new list. You will be redirected to a page where you can create your new list.
-2. Select New Contributor Insight to start a new Contributor Insight Page.
-3. Give your list a name.
-4. Choose your page visibility. You can choose to make your list public or private. By default, it is set to public. To create a private page, you can upgrade your account to a paid plan.
-5. Add contributors to your list by searching for their GitHub username, syncing your GitHub Team, or importing your GitHub Following.
+1. Click the "+" next to "Insights" in your sidebar.
+2. Select "New Contributor Insight" to start a new Contributor Insight Page.
+3. Give your page a name.
+4. Add contributors to your page by searching for their GitHub username, syncing your GitHub Team, or importing your GitHub Following.
+5. Choose your page visibility. You can choose to make your list public or private. By default, it is set to public. To create a private page, you can upgrade your account to a paid plan.
```
[the remark this answers is not in the document]
Comment (BekahHW) [reply docs/contributors/contributors-guide.md:190]: Sure. I just wrote some issues to get that changed. Nice catch.

File: docs/features/workspaces.md (hunk 28 above)
[the remark this answers is not in the document]
Comment (adiati98) [reply docs/features/workspaces.md:72]: Ah, now I see. You're right. Only "Your personal workspace" that has the edit button in the beginning.
Creating new workspace will take us the creation form as below.

Screenshot 2024-03-04 204657

I remember that you will add more details to the workspaces, but I'm not sure if this one of them. So, I throw this here, just in case. 😅

File: docs/contributors/contributors-guide.md (hunk 29 above)
[the remark this answers is not in the document]
Comment (adiati98) [reply docs/contributors/contributors-guide.md:190]: If we'll change it as per your issue on app, we can leave it as is. Otherwise, you can just commit them if it's a go. 😊

File: docs/features/workspaces.md (hunk 28 above)
[the remark this answers is not in the document]
Comment (CBID2) [reply docs/features/workspaces.md:72]: I think this could be a separate issue. What do you think @BekahHW?

**Comment by adiati98** [comment]
@BekahHW

I already have a screenshot to replace the one in "Activity" tab in [this comment](https://github.com/open-sauced/docs/pull/262#discussion_r1511677422).
But we can do this in next PR if you will.

If you've reviewed and approved the changes here, I think we can merge this in before it's getting much longer and more difficult to follow. Let's do the unresolved suggestions in the following PRs. Thank you😊

**Review by BekahHW — APPROVED** [review]
